name: whiskers

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@feat/working-directory
    with:
      args: |
        templates/config.tera
        templates/resources.tera
        templates/stylesheet.tera
    secrets: inherit
